# Generated by Django 3.0.7 on 2020-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
